on: [push]

jobs:
  copy_repo_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Step 1
        run: pwd
      - name: Step 2
        run: git -v
      - name: Step 3
        run: git status
