on: [push]

jobs:
  copy_repo_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Step 1
        run: pwd
      - name: Step 2
        run: git clone https://github.com/onehitdragon/godgon-webpage.git .
      - name: Step 3
        run: ls -a
      - name: Step 4
        run: git status
