on: [push]

jobs:
  copy_repo_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Step 2
        run: ls -a
      - name: Step 3
        uses: ./
        with:
          who-to-greet: VinhProIn
